# coding: utf-8

# flake8: noqa
"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-06-27T06:06:59Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
