# coding: utf-8

"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-06-27T06:06:59Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_aos_get(self) -> None:
        """Test case for aos_get

        """
        pass

    def test_aos_options(self) -> None:
        """Test case for aos_options

        """
        pass

    def test_aos_post(self) -> None:
        """Test case for aos_post

        """
        pass

    def test_batch_options(self) -> None:
        """Test case for batch_options

        """
        pass

    def test_batch_post(self) -> None:
        """Test case for batch_post

        """
        pass

    def test_ddb_list_messages_get(self) -> None:
        """Test case for ddb_list_messages_get

        """
        pass

    def test_ddb_list_messages_options(self) -> None:
        """Test case for ddb_list_messages_options

        """
        pass

    def test_ddb_list_sessions_get(self) -> None:
        """Test case for ddb_list_sessions_get

        """
        pass

    def test_ddb_list_sessions_options(self) -> None:
        """Test case for ddb_list_sessions_options

        """
        pass

    def test_ddb_options(self) -> None:
        """Test case for ddb_options

        """
        pass

    def test_ddb_post(self) -> None:
        """Test case for ddb_post

        """
        pass

    def test_etl_delete_execution_options(self) -> None:
        """Test case for etl_delete_execution_options

        """
        pass

    def test_etl_delete_execution_post(self) -> None:
        """Test case for etl_delete_execution_post

        """
        pass

    def test_etl_execution_get(self) -> None:
        """Test case for etl_execution_get

        """
        pass

    def test_etl_execution_options(self) -> None:
        """Test case for etl_execution_options

        """
        pass

    def test_etl_list_execution_get(self) -> None:
        """Test case for etl_list_execution_get

        """
        pass

    def test_etl_list_execution_options(self) -> None:
        """Test case for etl_list_execution_options

        """
        pass

    def test_etl_list_workspace_get(self) -> None:
        """Test case for etl_list_workspace_get

        """
        pass

    def test_etl_list_workspace_options(self) -> None:
        """Test case for etl_list_workspace_options

        """
        pass

    def test_etl_options(self) -> None:
        """Test case for etl_options

        """
        pass

    def test_etl_post(self) -> None:
        """Test case for etl_post

        """
        pass

    def test_etl_upload_s3_url_options(self) -> None:
        """Test case for etl_upload_s3_url_options

        """
        pass

    def test_etl_upload_s3_url_post(self) -> None:
        """Test case for etl_upload_s3_url_post

        """
        pass

    def test_extract_options(self) -> None:
        """Test case for extract_options

        """
        pass

    def test_extract_post(self) -> None:
        """Test case for extract_post

        """
        pass

    def test_llm_options(self) -> None:
        """Test case for llm_options

        """
        pass

    def test_llm_post(self) -> None:
        """Test case for llm_post

        """
        pass

    def test_prompt_get(self) -> None:
        """Test case for prompt_get

        """
        pass

    def test_prompt_options(self) -> None:
        """Test case for prompt_options

        """
        pass

    def test_prompt_post(self) -> None:
        """Test case for prompt_post

        """
        pass

    def test_root_options(self) -> None:
        """Test case for root_options

        """
        pass


if __name__ == '__main__':
    unittest.main()
