# coding: utf-8

"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-06-14T11:08:22Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_aos_post(self) -> None:
        """Test case for aos_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
