project: AI Customer Service
version: 0.0.1
author: IndustryBuilders Team
login:
  user: 
    value: username
    disabled: true
  sns: 
    value: sns
    disabled: true
  oidc:
    value: oidc
    providers:
      - name: authing
        label: Authing
        clientId: 66b769cf5c2d439dfd37f237
        redirectUri: https://demo-center.authing.cn
      - name: cognito
        label: Cognito
        # client_id: 6fsdfdsdddddsadsf434ssd3
        # user_pool_id: us-east-1_VeItKBhLQ
        # domain: us-east-1veitkbhlq.auth.us-east-1.amazoncognito.com
        # region: us-east-1
        # diabled: true
  sso:
    midway:
      provider: auth-hub-midway
      user_pool_id: us-east-1_IM5zGhc8w
      user_pool_client_id: 2m165ontae26nt91gesos569pl
      auth:
        domain: us-east-1im5zghc8w.auth.us-east-1.amazoncognito.com
        redirect_signin_local: http://localhost:3088/login
        redirect_signout_local: http://localhost:3088

  