# coding: utf-8

# flake8: noqa
"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-07-01T14:38:20Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.intellapico_kbf_xmyu1_w8_nr import IntellapicoKbfXMYu1W8Nr
