# coding: utf-8

"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-07-10T06:22:41Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class IntellapicoJAOkR451tRepItemsInner(BaseModel):
    """
    IntellapicoJAOkR451tRepItemsInner
    """ # noqa: E501
    execution_id: StrictStr = Field(alias="executionId")
    s3_path: StrictStr = Field(alias="s3Path")
    create_time: StrictStr = Field(alias="createTime")
    s3_prefix: StrictStr = Field(alias="s3Prefix")
    s3_bucket: StrictStr = Field(alias="s3Bucket")
    status: StrictStr
    __properties: ClassVar[List[str]] = ["executionId", "s3Path", "createTime", "s3Prefix", "s3Bucket", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntellapicoJAOkR451tRepItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntellapicoJAOkR451tRepItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "executionId": obj.get("executionId"),
            "s3Path": obj.get("s3Path"),
            "createTime": obj.get("createTime"),
            "s3Prefix": obj.get("s3Prefix"),
            "s3Bucket": obj.get("s3Bucket"),
            "status": obj.get("status")
        })
        return _obj


