# coding: utf-8

"""
    llmApi

    This service serves the LLM API.

    The version of the OpenAPI document: 2024-07-22T05:29:35Z
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.intellapico_jox_fkq_jzeoju_config import IntellapicoJOxFkqJZEOJUConfig
from openapi_client.models.intellapico_jox_fkq_jzeoju_items_inner import IntellapicoJOxFkqJZEOJUItemsInner
from typing import Optional, Set
from typing_extensions import Self

class IntellapicoJOxFkqJZEOJU(BaseModel):
    """
    IntellapicoJOxFkqJZEOJU
    """ # noqa: E501
    config: Optional[IntellapicoJOxFkqJZEOJUConfig] = Field(default=None, alias="Config")
    items: Optional[List[IntellapicoJOxFkqJZEOJUItemsInner]] = Field(default=None, alias="Items")
    count: Optional[StrictInt] = Field(default=None, alias="Count")
    __properties: ClassVar[List[str]] = ["Config", "Items", "Count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntellapicoJOxFkqJZEOJU from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['Config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntellapicoJOxFkqJZEOJU from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Config": IntellapicoJOxFkqJZEOJUConfig.from_dict(obj["Config"]) if obj.get("Config") is not None else None,
            "Items": [IntellapicoJOxFkqJZEOJUItemsInner.from_dict(_item) for _item in obj["Items"]] if obj.get("Items") is not None else None,
            "Count": obj.get("Count")
        })
        return _obj


