
table_prompt_dict = {}
table_prompt_dict['table_haiku-20240307v1-0_20240407063835']="""
Event：存储的是一家药企的举办市场活动/会议的信息
- name: trty_name, datatype: VARCHAR, comment: 岗位名称
  annotataion:
- name: event_name, datatype: VARCHAR, comment: 活动名称
  annotataion:
- name: event_date, datatype: DATE, comment: 活动时间
  annotataion:
- name: brand, datatype: VARCHAR, comment: 产品
  annotataion: 示例数据，Forxiga 中文名称是安达唐, Tagrisso,Breztri Aero
- name: event_city, datatype: VARCHAR, comment: 活动城市
  annotataion:
- name: event_type, datatype: VARCHAR, comment: 活动类型
  annotataion:
- name: event_status, datatype: VARCHAR, comment: 活动状态
  annotataion: 示例数据，Event Approved for Closing,Event Blocked,Event Cancelled,Event Rejected,Under Rework for Closing,Available for Closing,New,Under Rework,Event Submitted for Closing,Event Submitted
 
internal_sales: 是内部销量表(药品在内部代理和销售大区的销售数据), 存储销售岗位名称、产品、部门、买方所在省、买方所在区域、销售金额等信息, 如果涉及销售区域和买家可以在这里查询。
- name: sales_date, datatype: DATE, comment: 销售日期
  annotataion:
- name: trty_name, datatype: VARCHAR, comment: 销售岗位名称
  annotataion:
- name: brand, datatype: VARCHAR, comment: 产品
  annotataion: 示例数据为,Forxiga(中文名称安达唐)，Tagrisso(中文名称泰瑞沙)，Breztri Aero(中文名称倍择瑞)
- name: bu, datatype: VARCHAR, comment: 销售部门
  annotataion: 示例数据为,RI&B, RGI,OBU,EC,Eagle,CVRM,CHC,BBU_County
- name: sub_bu, datatype: VARCHAR, comment: 销售子部门
  annotataion: 示例数据为,LC,CHC,BBU_County,IPT,GNR,OBU_County,EC
- name: province_name, datatype: VARCHAR, comment: 买方所在省, 值是中国所有省份,如广东
  annotataion:
- name: area_name, datatype: VARCHAR, comment: 买方所在区
  annotataion: 示例数据为,东部地区,中部地区,北部地区,南部地区,西部地区
- name: region_name, datatype: VARCHAR, comment: 销售大区
  annotataion:
- name: region_center_name, datatype: VARCHAR, comment: 销售大区中心
  annotataion:
- name: inst_name, datatype: VARCHAR, comment: 买方名称,值大多是各类购买药品的医院/诊所名称
  annotataion:
- name: sales_val, datatype: DECIMAL, comment: 销售金额
  annotataion:
- name: target_val, datatype: DECIMAL, comment: 目标销售金额
  annotataion:
 
external_sales: 是外部销量表(药品在市场上销售的数据), 存储销量来源、市场、产品、销售日期、销售金额等字段, 如果涉及市场排名可以在这里查询。存储的是多家药企的外部销售数据, 一个药企可能销售多种药, 每种药每段时间在市场上销量为一行数据。
 
- name: source, datatype: VARCHAR, comment: 数据来源, 只有'aia','ims'两种值
  annotataion:
- name: market, datatype: VARCHAR, comment: 市场
  annotataion:
- name: manufacturer, datatype: VARCHAR, comment:
  annotataion:
- name: brand, datatype: VARCHAR, comment: 产品
  annotataion:
- name: is_az, datatype: VARCHAR, comment: 是否是AZ的产品
  annotataion: 数值只有:Y或者N
- name: sales_date, datatype: DATE, comment: 销售日期
  annotataion: 日期的格式是2023-01-01
- name: sales_val, datatype: DECIMAL, comment: 销售金额, 数据类型是(numeric)
  annotataion:
 
listed_brand: 存储的是药企的客户每次来采购药品的数据
 
- name: inst_name, datatype: VARCHAR, comment: 买方名称
  annotataion:
- name: list_date, datatype: DATE, comment: 采购时间
  annotataion: 示例时间是，2023-02-01
- name: brand, datatype: VARCHAR, comment: 产品
  annotataion: 示例数据包括Forxiga,Tagrisso,Breztri Aerok
"""

table_prompt_dict['table_sonnet-20240229v1-0_20240407063835']="""
CREATE TABLE zenmakeovermatch.account (
    id bigint ENCODE zstd
    distkey

        country_code character varying(64) ENCODE zstd,
        country_name character varying(64) ENCODE zstd,
        region_code character varying(64) ENCODE zstd,
        region_name character varying(64) ENCODE zstd,
        city character varying(64) ENCODE zstd,
        time_zone character varying(64) ENCODE zstd,
        platform integer ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        updated_at timestamp without time zone ENCODE zstd,
        old_device_id character varying(64) ENCODE zstd,
        facebook_id character varying(64) ENCODE zstd,
        facebook_name character varying(64) ENCODE zstd,
        facebook_email character varying(64) ENCODE zstd,
        migrated_from character varying(64) ENCODE zstd,
        erased_by character varying(64) ENCODE zstd,
        group_ids character varying(64) ENCODE zstd,
        id_string character varying(65535) ENCODE lzo,
        updated_at_string character varying(65535) ENCODE lzo,
        platform_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (updated_at);

CREATE TABLE zenmakeovermatch.common_game_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        common_game_event_type character varying(128) ENCODE zstd,
        params super ENCODE zstd,
        extras super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);
  
CREATE TABLE zenmakeovermatch.common_monetization_ad_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        monetization_event_type character varying(64) ENCODE zstd,
        reason character varying(128) ENCODE zstd,
        placement character varying(128) ENCODE zstd,
        params super ENCODE zstd,
        extras super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.common_monetization_iap_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        monetization_event_type character varying(64) ENCODE zstd,
        reason character varying(128) ENCODE zstd,
        placement character varying(128) ENCODE zstd,
        product_id character varying(128) ENCODE zstd,
        transction_id character varying(128) ENCODE zstd,
        params super ENCODE zstd,
        extras super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.common_ops_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        event_id character varying(128) ENCODE zstd,
        event_type character varying(64) ENCODE zstd,
        event_action character varying(128) ENCODE zstd,
        params super ENCODE zstd,
        extras super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.debug_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        infos super ENCODE zstd,
        tags super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.decoration (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        coin bigint ENCODE zstd,
        energy bigint ENCODE zstd,
        star bigint ENCODE zstd,
        room bigint ENCODE zstd,
        node_count bigint ENCODE zstd,
        retain_day_local bigint ENCODE zstd,
        active_day_local bigint ENCODE zstd,
        passed_level_count bigint ENCODE zstd,
        user_layer bigint ENCODE zstd,
        layer_order bigint ENCODE zstd,
        infinity_energy bigint ENCODE zstd,
        current_match_money bigint ENCODE zstd,
        feature character varying(32) ENCODE zstd,
        room_id bigint ENCODE zstd,
        room_enter_time bigint ENCODE zstd,
        room_task_coin bigint ENCODE zstd,
        room_task_gem bigint ENCODE zstd,
        room_item_id bigint ENCODE zstd,
        item_style_id character varying(64) ENCODE zstd,
        item_decision_time bigint ENCODE zstd,
        item_change_time bigint ENCODE zstd,
        room_level bigint ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        room_id_string character varying(65535) ENCODE lzo,
        current_match_money_string character varying(65535) ENCODE lzo,
        user_group_ad_string character varying(65535) ENCODE lzo,
        infinity_energy_string character varying(65535) ENCODE lzo,
        retain_day_local_string character varying(65535) ENCODE lzo,
        item_decision_time_string character varying(65535) ENCODE lzo,
        item_change_time_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        node_count_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        passed_level_count_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        room_enter_time_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        star_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo,
        room_item_id_string character varying(65535) ENCODE lzo,
        active_day_local_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        room_task_gem_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        room_task_coin_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        room_level_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        room_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.error_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        protocol character varying(128) ENCODE zstd,
        errno character varying(128) ENCODE zstd,
        errmsg character varying(1024) ENCODE zstd,
        stack character varying(1024) ENCODE zstd,
        log_type character varying(128) ENCODE zstd,
        stacks super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.game_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        coin bigint ENCODE zstd,
        energy bigint ENCODE zstd,
        star bigint ENCODE zstd,
        room bigint ENCODE zstd,
        node_count bigint ENCODE zstd,
        retain_day_local bigint ENCODE zstd,
        active_day_local bigint ENCODE zstd,
        passed_level_count bigint ENCODE zstd,
        user_layer bigint ENCODE zstd,
        layer_order bigint ENCODE zstd,
        infinity_energy bigint ENCODE zstd,
        current_match_money bigint ENCODE zstd,
        game_event_type character varying(64) ENCODE zstd,
        is_auto boolean ENCODE zstd,
        status character varying(16) ENCODE zstd,
        data1 character varying(128) ENCODE zstd,
        data2 character varying(128) ENCODE zstd,
        data3 character varying(128) ENCODE zstd,
        data4 character varying(128) ENCODE zstd,
        extras super ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        current_match_money_string character varying(65535) ENCODE lzo,
        user_group_ad_string character varying(65535) ENCODE lzo,
        infinity_energy_string character varying(65535) ENCODE lzo,
        retain_day_local_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        node_count_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        is_auto_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        passed_level_count_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        star_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo,
        active_day_local_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        room_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.iap_detail (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        iap_step character varying(32) ENCODE zstd,
        product_id character varying(128) ENCODE zstd,
        payment_id character varying(64) ENCODE zstd,
        data character varying(65535) ENCODE zstd,
        transaction_id character varying(256) ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.item_change (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        coin bigint ENCODE zstd,
        energy bigint ENCODE zstd,
        star bigint ENCODE zstd,
        room bigint ENCODE zstd,
        node_count bigint ENCODE zstd,
        retain_day_local bigint ENCODE zstd,
        active_day_local bigint ENCODE zstd,
        passed_level_count bigint ENCODE zstd,
        user_layer bigint ENCODE zstd,
        layer_order bigint ENCODE zstd,
        infinity_energy bigint ENCODE zstd,
        current_match_money bigint ENCODE zstd,
        item character varying(64) ENCODE zstd,
        amount bigint ENCODE zstd,
        current bigint ENCODE zstd,
        reason character varying(128) ENCODE zstd,
        data1 character varying(64) ENCODE zstd,
        data2 character varying(64) ENCODE zstd,
        data3 character varying(64) ENCODE zstd,
        data4 character varying(64) ENCODE zstd,
        item_sub_type character varying(64) ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        current_match_money_string character varying(65535) ENCODE lzo,
        user_group_ad_string character varying(65535) ENCODE lzo,
        infinity_energy_string character varying(65535) ENCODE lzo,
        retain_day_local_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        node_count_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        passed_level_count_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        amount_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        star_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo,
        active_day_local_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        current_string character varying(65535) ENCODE lzo,
        room_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

  CREATE TABLE zenmakeovermatch.level_info (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        coin bigint ENCODE zstd,
        energy bigint ENCODE zstd,
        star bigint ENCODE zstd,
        room bigint ENCODE zstd,
        node_count bigint ENCODE zstd,
        retain_day_local bigint ENCODE zstd,
        active_day_local bigint ENCODE zstd,
        passed_level_count bigint ENCODE zstd,
        user_layer bigint ENCODE zstd,
        layer_order bigint ENCODE zstd,
        infinity_energy bigint ENCODE zstd,
        current_match_money bigint ENCODE zstd,
        level_count bigint ENCODE zstd,
        layout_id bigint ENCODE zstd,
        level_difficulty bigint ENCODE zstd,
        add_five_count bigint ENCODE zstd,
        level_play_time bigint ENCODE zstd,
        level_result character varying(16) ENCODE zstd,
        pre_rocket bigint ENCODE zstd,
        pre_bomb bigint ENCODE zstd,
        pre_lightball bigint ENCODE zstd,
        win_challenge bigint ENCODE zstd,
        left_goal_count bigint ENCODE zstd,
        left_step_count bigint ENCODE zstd,
        power_hammer bigint ENCODE zstd,
        power_plane bigint ENCODE zstd,
        power_rocket bigint ENCODE zstd,
        power_shuffle bigint ENCODE zstd,
        fly_gen_count bigint ENCODE zstd,
        rocket_gen_count bigint ENCODE zstd,
        bomb_gen_count bigint ENCODE zstd,
        lightball_gen_count bigint ENCODE zstd,
        total_step bigint ENCODE zstd,
        total_goal bigint ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        add_five_count_string character varying(65535) ENCODE lzo,
        current_match_money_string character varying(65535) ENCODE lzo,
        infinity_energy_string character varying(65535) ENCODE lzo,
        retain_day_local_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        lightball_gen_count_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        level_count_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        bomb_gen_count_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        layout_id_string character varying(65535) ENCODE lzo,
        power_shuffle_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        total_goal_string character varying(65535) ENCODE lzo,
        left_step_count_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        pre_lightball_string character varying(65535) ENCODE lzo,
        left_goal_count_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        win_challenge_string character varying(65535) ENCODE lzo,
        level_play_time_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        rocket_gen_count_string character varying(65535) ENCODE lzo,
        power_rocket_string character varying(65535) ENCODE lzo,
        power_plane_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        user_group_ad_string character varying(65535) ENCODE lzo,
        level_difficulty_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        node_count_string character varying(65535) ENCODE lzo,
        total_step_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        passed_level_count_string character varying(65535) ENCODE lzo,
        fly_gen_count_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        pre_rocket_string character varying(65535) ENCODE lzo,
        star_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo,
        active_day_local_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        power_hammer_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        pre_bomb_string character varying(65535) ENCODE lzo,
        room_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);

CREATE TABLE zenmakeovermatch.payment (
    payment_id character varying(128) ENCODE zstd,
    transaction_id character varying(128) ENCODE zstd,
    receipt character varying(65535) ENCODE zstd,
    platform integer ENCODE zstd,
    player_id bigint ENCODE zstd,
    device_id character varying(128) ENCODE zstd,
    facebook_id character varying(128) ENCODE zstd,
    product_id character varying(128) ENCODE zstd,
    product_type character varying(128) ENCODE zstd,
    product_count integer ENCODE zstd,
    price_us double precision ENCODE zstd,
    ip character varying(128) ENCODE zstd,
    status integer ENCODE zstd,
    is_test boolean ENCODE zstd,
    purchase_token character varying(256) ENCODE zstd,
    created_at timestamp without time zone ENCODE zstd,
    updated_at timestamp without time zone ENCODE zstd,
    product_count_string character varying(65535) ENCODE lzo,
    updated_at_string character varying(65535) ENCODE lzo,
    is_test_string character varying(65535) ENCODE lzo,
    platform_string character varying(65535) ENCODE lzo,
    created_at_string character varying(65535) ENCODE lzo,
    status_string character varying(65535) ENCODE lzo,
    price_us_string character varying(65535) ENCODE lzo,
    player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE AUTO;

CREATE TABLE zenmakeovermatch.player (
    id bigint ENCODE zstd
    distkey
,
        country_code character varying(64) ENCODE zstd,
        country_name character varying(64) ENCODE zstd,
        region_code character varying(64) ENCODE zstd,
        region_name character varying(64) ENCODE zstd,
        city character varying(64) ENCODE zstd,
        time_zone character varying(64) ENCODE zstd,
        platform integer ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        updated_at timestamp without time zone ENCODE zstd,
        old_device_id character varying(64) ENCODE zstd,
        facebook_id character varying(64) ENCODE zstd,
        facebook_name character varying(64) ENCODE zstd,
        facebook_email character varying(64) ENCODE zstd,
        migrated_from character varying(64) ENCODE zstd,
        erased_by character varying(64) ENCODE zstd,
        group_ids character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        email character varying(64) ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        idfv character varying(64) ENCODE zstd,
        gaid character varying(64) ENCODE zstd,
        locale character varying(64) ENCODE zstd,
        country character varying(64) ENCODE zstd,
    region
        character varying(64) ENCODE zstd,
        timezone character varying(64) ENCODE zstd,
        res_version character varying(64) ENCODE zstd,
        app_version character varying(64) ENCODE zstd,
        invite_code character varying(64) ENCODE zstd,
        iap_count integer ENCODE zstd,
        iap_total integer ENCODE zstd,
        iap_last_time timestamp without time zone ENCODE zstd,
        iap_first_time timestamp without time zone ENCODE zstd,
        firebase_instance_id character varying(64) ENCODE zstd,
        apple_account_id character varying(64) ENCODE zstd,
        ads_predict_user_group integer ENCODE zstd,
        marketing super ENCODE zstd,
        ads_user_group_marketing_override boolean ENCODE zstd,
        active_data super ENCODE zstd,
        ad_count_reset_time bigint ENCODE zstd,
        ad_count_stage_state bigint ENCODE zstd,
        ad_reward_watched_count bigint ENCODE zstd,
        remote_group_id_datas super ENCODE zstd,
        config_hub super ENCODE zstd,
        coin integer ENCODE zstd,
        star character varying(1024) ENCODE zstd,
        energy integer ENCODE zstd,
        last_level_ret integer ENCODE zstd,
        last_played_level integer ENCODE zstd,
        last_level_diff integer ENCODE zstd,
        played_level_count integer ENCODE zstd,
        current_room integer ENCODE zstd,
        user_layer integer ENCODE zstd,
        layer_order integer ENCODE zstd,
        id_hex character varying(16) ENCODE zstd,
        iap_level integer ENCODE zstd,
        source character varying(64) ENCODE zstd,
        is_organic boolean ENCODE zstd,
        is_cheat boolean ENCODE zstd,
        is_test_player boolean ENCODE zstd,
        marketing_partner character varying(256) ENCODE zstd,
        marketing_network_name character varying(256) ENCODE zstd,
        marketing_campaign_name character varying(256) ENCODE zstd,
        marketing_adgroup_name character varying(256) ENCODE zstd,
        marketing_creative_name character varying(256) ENCODE zstd,
        played_level_count_string character varying(65535) ENCODE lzo,
        iap_last_time_string character varying(65535) ENCODE lzo,
        platform_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        ad_reward_watched_count_string character varying(65535) ENCODE lzo,
        ad_count_stage_state_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        updated_at_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        iap_first_time_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        iap_level_string character varying(65535) ENCODE lzo,
        id_string character varying(65535) ENCODE lzo,
        last_level_ret_string character varying(65535) ENCODE lzo,
        current_room_string character varying(65535) ENCODE lzo,
        last_level_diff_string character varying(65535) ENCODE lzo,
        is_cheat_string character varying(65535) ENCODE lzo,
        ads_predict_user_group_string character varying(65535) ENCODE lzo,
        is_organic_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        last_played_level_string character varying(65535) ENCODE lzo,
        is_test_player_string character varying(65535) ENCODE lzo,
        ads_user_group_marketing_override_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        ad_count_reset_time_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (updated_at);

CREATE TABLE zenmakeovermatch.profile (
    id bigint ENCODE zstd
    distkey
,
        device_id character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        email character varying(64) ENCODE zstd,
        facebook_id character varying(64) ENCODE zstd,
        facebook_name character varying(256) ENCODE zstd,
        facebook_email character varying(256) ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        idfv character varying(64) ENCODE zstd,
        gaid character varying(64) ENCODE zstd,
        platform integer ENCODE zstd,
        locale character varying(64) ENCODE zstd,
        country character varying(64) ENCODE zstd,
    region
        character varying(64) ENCODE zstd,
        timezone character varying(64) ENCODE zstd,
        res_version character varying(64) ENCODE zstd,
        app_version character varying(64) ENCODE zstd,
        invite_code character varying(64) ENCODE zstd,
        iap_count integer ENCODE zstd,
        iap_total integer ENCODE zstd,
        iap_last_time timestamp without time zone ENCODE zstd,
        iap_first_time timestamp without time zone ENCODE zstd,
        firebase_instance_id character varying(64) ENCODE zstd,
        apple_account_id character varying(64) ENCODE zstd,
        ads_predict_user_group integer ENCODE zstd,
        marketing super ENCODE zstd,
        ads_user_group_marketing_override boolean ENCODE zstd,
        active_data super ENCODE zstd,
        ad_count_reset_time bigint ENCODE zstd,
        ad_count_stage_state bigint ENCODE zstd,
        ad_reward_watched_count bigint ENCODE zstd,
        remote_group_id_datas super ENCODE zstd,
        config_hub super ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        updated_at timestamp without time zone ENCODE zstd,
        coin integer ENCODE zstd,
        star character varying(1024) ENCODE zstd,
        energy integer ENCODE zstd,
        last_level_ret integer ENCODE zstd,
        last_played_level integer ENCODE zstd,
        last_level_diff integer ENCODE zstd,
        played_level_count integer ENCODE zstd,
        current_room integer ENCODE zstd,
        user_layer integer ENCODE zstd,
        layer_order integer ENCODE zstd,
        id_string character varying(65535) ENCODE lzo,
        played_level_count_string character varying(65535) ENCODE lzo,
        last_level_ret_string character varying(65535) ENCODE lzo,
        current_room_string character varying(65535) ENCODE lzo,
        last_level_diff_string character varying(65535) ENCODE lzo,
        iap_last_time_string character varying(65535) ENCODE lzo,
        ads_predict_user_group_string character varying(65535) ENCODE lzo,
        platform_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        ad_reward_watched_count_string character varying(65535) ENCODE lzo,
        updated_at_string character varying(65535) ENCODE lzo,
        ad_count_stage_state_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        coin_string character varying(65535) ENCODE lzo,
        last_played_level_string character varying(65535) ENCODE lzo,
        energy_string character varying(65535) ENCODE lzo,
        ads_user_group_marketing_override_string character varying(65535) ENCODE lzo,
        iap_first_time_string character varying(65535) ENCODE lzo,
        user_layer_string character varying(65535) ENCODE lzo,
        layer_order_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        ad_count_reset_time_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (updated_at);

CREATE TABLE zenmakeovermatch.session_event (
    player_id bigint ENCODE zstd
    distkey
,
        player_type character varying(32) ENCODE zstd,
        player_name character varying(128) ENCODE zstd,
        player_email character varying(128) ENCODE zstd,
        facebook_id character varying(32) ENCODE zstd,
        facebook_email character varying(128) ENCODE zstd,
        facebook_name character varying(128) ENCODE zstd,
        platform character varying(16) ENCODE zstd,
        revenue_usd_cents bigint ENCODE zstd,
        member boolean ENCODE zstd,
        member_age bigint ENCODE zstd,
        member_time bigint ENCODE zstd,
        environment character varying(16) ENCODE zstd,
        client_version character varying(32) ENCODE zstd,
        resource_version character varying(32) ENCODE zstd,
        installed_at timestamp without time zone ENCODE zstd,
        created_at timestamp without time zone ENCODE zstd,
        adjust_id character varying(64) ENCODE zstd,
        adid character varying(64) ENCODE zstd,
        idfa character varying(64) ENCODE zstd,
        device_id character varying(64) ENCODE zstd,
        device_os_name character varying(64) ENCODE zstd,
        device_os_version character varying(64) ENCODE zstd,
        device_screen_resolution character varying(64) ENCODE zstd,
        device_language character varying(64) ENCODE zstd,
        device_country character varying(64) ENCODE zstd,
        device_memory character varying(64) ENCODE zstd,
        device_model character varying(64) ENCODE zstd,
        device_timezone character varying(64) ENCODE zstd,
        device_type character varying(64) ENCODE zstd,
        network_type character varying(64) ENCODE zstd,
        ip character varying(64) ENCODE zstd,
        local_version bigint ENCODE zstd,
        remote_version_ack bigint ENCODE zstd,
        remote_version_local bigint ENCODE zstd,
        has_login boolean ENCODE zstd,
        has_network boolean ENCODE zstd,
        current_member_type character varying(64) ENCODE zstd,
        abtests character varying(1024) ENCODE zstd,
        client_version_name character varying(64) ENCODE zstd,
        user_group_ad bigint ENCODE zstd,
        common_extras super ENCODE zstd,
        user_groups super ENCODE zstd,
        campaign_type_code bigint ENCODE zstd,
        game_scheme character varying(64) ENCODE zstd,
        sequence bigint ENCODE zstd,
        abtest_map super ENCODE zstd,
        initial_client_version character varying(32) ENCODE zstd,
        iap_count bigint ENCODE zstd,
        iap_total bigint ENCODE zstd,
        session_start_time timestamp without time zone ENCODE zstd,
        session_end_time timestamp without time zone ENCODE zstd,
        time timestamp without time zone ENCODE zstd,
        load_date character varying(32) ENCODE zstd,
        user_group_ad_string character varying(65535) ENCODE lzo,
        session_start_time_string character varying(65535) ENCODE lzo,
        local_version_string character varying(65535) ENCODE lzo,
        sequence_string character varying(65535) ENCODE lzo,
        campaign_type_code_string character varying(65535) ENCODE lzo,
        iap_count_string character varying(65535) ENCODE lzo,
        member_time_string character varying(65535) ENCODE lzo,
        revenue_usd_cents_string character varying(65535) ENCODE lzo,
        time_string character varying(65535) ENCODE lzo,
        iap_total_string character varying(65535) ENCODE lzo,
        installed_at_string character varying(65535) ENCODE lzo,
        member_age_string character varying(65535) ENCODE lzo,
        session_end_time_string character varying(65535) ENCODE lzo,
        member_string character varying(65535) ENCODE lzo,
        has_network_string character varying(65535) ENCODE lzo,
        remote_version_local_string character varying(65535) ENCODE lzo,
        has_login_string character varying(65535) ENCODE lzo,
        remote_version_ack_string character varying(65535) ENCODE lzo,
        created_at_string character varying(65535) ENCODE lzo,
        player_id_string character varying(65535) ENCODE lzo
) DISTSTYLE KEY
SORTKEY
    (time);
"""

table_prompt_dict['guidance_haiku-20240307v1-0_20240407063835'] = """
you should always keep the words from question unchanges when writing SQL. \n\n
"""

table_prompt_dict['guidance_sonnet-20240229v1-0_20240407063835'] = """
you should always keep the words from question unchanges when writing SQL. \n\n
you should always use zenmakeovermatch as schema name. For example, use zenmakeovermatch.account instead of account\n\n
when sql question is about PV (page view) or UV (user view), you should consider event name including _page_view and _screen_view \n\n
you should always use event id to count the occurance of event name \n\n
"""
# divide the sales volume of the product or competing products rolling forward 3 months from the latest month of data by sales volume in the same time period in the market to get R3M MS% (YoY) or 滚动3个月市场占比.
# use the MS% of the product or competitive product rolled forward 3 months from the latest month of data and subtract the MS% of the same period last year to get Δ MS% (YoY) or 滚动3个月市场占比变化.

# support_funtions = ['table', 'guidance']

# support_model_ids_map = {
#     "anthropic.claude-3-haiku-20240307-v1:0":"haiku-20240307v1-0",
#     "anthropic.claude-3-sonnet-20240229-v1:0":"sonnet-20240229v1-0"
# }

# support_versions = ['20240407063835']

class SQLPromptMapper:
    def __init__(self):
        self.variable_map = table_prompt_dict

    def get_variable(self, name):
        return self.variable_map.get(name)